

networks:
  default:
    driver: bridge
    name: roboshop
    external: true  # Uncomment if you created the network outside

services:
  mongodb:
    image: vinod9072/mongodb:v1
    container_name: mongodb

  catalogue:
    image: vinod9072/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  redis:
    image: redis:7.0
    container_name: redis

  user:
    image: vinod9072/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    image: vinod9072/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis

  mysql:
    image: vinod9072/mysql:v1
    container_name: mysql

  shipping:
    image: vinod9072/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment:
    image: vinod9072/payment:v1
    container_name: payment
    environment:
    CART_HOST: cart
    CART_PORT: 8080
    USER_HOST: user
    USER_PORT: 8080
    AMQP_HOST: rabbitmq
    AMQP_USER: roboshop
    AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user



