  networks:
    default:
    driver: bridge
    name: roboshop
    external: true  # I created network outside so i mentioned external ture  
    
  services:
    mongodb:
      image: vinod9072/mongodb:v1
      container_name: mongodb
    catalogue:
      image: vinod9072/catalogue:v1
      container_name: catalogue
      depends_on:
      - mongodb
    redis:
      image: redis:7.0
      container_name: redis
    user:
      image: vinod9072/user:v1
      container_name: user
      depends_on:
      - mongodb
      - redis
    cart:
      image: vinod9072/cart:v1
      container_name: cart
      depends_on:
      - catalogue
      - redis
    mysql:
      image: vinod9072/mysql:v1
      container_name: mysql
    shipping:
      image: vinod9072/shipping:v1
      container_name: shipping
      depends_on:
      - mysql
      - cart


    


